import type { Metadata } from "next";
import Navbar from "../ui/navbar";
import Footer from "../ui/footer";

export const metadata: Metadata = {
    title: {
        template: "About | %s",
        default: "About | Alfazh",
    },
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="relative dark lg:max-w-[1600px] mx-auto">
            <body>
                <Navbar />
                <main className="pt-32 pb-20 mx-auto lg:w-3/4 md:w-5/6 w-11/12 justify-center items-center">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
